@component('mail::message')
# Moderation alert

**Event:** {{ $event === 'block' ? 'User blocked' : 'Content reported' }}

**By:** {{ $reporterLabel }}

**Target:** {{ $targetLabel }}

@if ($reason)
**Reason:** {{ $reason }}
@endif

@if ($contentSummary)
**Details:** {{ $contentSummary }}
@endif

@if (! empty($details))
@component('mail::table')
| Field | Value |
| :---- | :---- |
@foreach ($details as $field => $value)
| {{ $field }} | {{ $value ?? '—' }} |
@endforeach
@endcomponent
@endif

This is an automated notification generated by the Kolabing UGC moderation system (App Review Guideline 1.2).

Thanks,<br>
{{ config('app.name') }}
@endcomponent
