<?php

declare(strict_types=1);

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

/**
 * A Member is always a Follower — including the ones who joined before that was
 * true (kolabing-app#146).
 *
 * Without this, every membership that predates the change is a "member who does
 * not follow", which is the exact state the ticket exists to make impossible:
 * their communities would be missing from the Following feed, and the app would
 * offer them a Follow button for something they already belong to.
 *
 * Insert-only and idempotent — it adds the rows that are missing and touches
 * nothing that exists, so re-running it is a no-op. Deliberately does NOT go the
 * other way: a follower is not made a member by anything, ever.
 */
return new class extends Migration
{
    public function up(): void
    {
        // Chunked rather than one INSERT..SELECT: `community_followers.id` is a
        // UUID generated by the app, not the database, so the ids have to be
        // made here.
        DB::table('community_members')
            ->select('community_id', 'profile_id', 'joined_at')
            ->orderBy('id')
            ->chunk(500, function ($members): void {
                $now = now();
                $rows = [];

                foreach ($members as $member) {
                    $exists = DB::table('community_followers')
                        ->where('community_id', $member->community_id)
                        ->where('profile_id', $member->profile_id)
                        ->exists();

                    if ($exists) {
                        continue;
                    }

                    $rows[] = [
                        'id' => (string) Str::uuid(),
                        'community_id' => $member->community_id,
                        'profile_id' => $member->profile_id,
                        // The follow is as old as the membership: it was always
                        // implied, it just was not recorded.
                        'followed_at' => $member->joined_at ?? $now,
                        'created_at' => $now,
                        'updated_at' => $now,
                    ];
                }

                if ($rows !== []) {
                    DB::table('community_followers')->insert($rows);
                }
            });
    }

    /**
     * Not reversible, on purpose. Deleting follows here would remove rows people
     * created deliberately — there is no way to tell a backfilled follow from
     * one someone pressed a button for, and guessing wrong loses real intent.
     */
    public function down(): void
    {
        // Intentionally empty.
    }
};
